In [11]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [12]:
df = pd.read_csv('laptop_price.csv', encoding = 'latin1')
df.head()
df['Cpu'].unique()

<StringArray>
[                'Intel Core i5 2.3GHz',
                 'Intel Core i5 1.8GHz',
           'Intel Core i5 7200U 2.5GHz',
                 'Intel Core i7 2.7GHz',
                 'Intel Core i5 3.1GHz',
              'AMD A9-Series 9420 3GHz',
                 'Intel Core i7 2.2GHz',
           'Intel Core i7 8550U 1.8GHz',
           'Intel Core i5 8250U 1.6GHz',
             'Intel Core i3 6006U 2GHz',
 ...
                  'Intel Core M 1.1GHz',
 'Intel Pentium Dual Core 4405Y 1.5GHz',
 'Intel Pentium Quad Core N3700 1.6GHz',
             'Intel Core M 6Y54 1.1GHz',
          'Intel Core i7 6500U 2.50GHz',
   'Intel Celeron Dual Core N3350 2GHz',
        'Samsung Cortex A72&A53 2.0GHz',
             'AMD E-Series 9000 2.2GHz',
             'Intel Core M 6Y30 0.9GHz',
            'AMD A9-Series 9410 2.9GHz']
Length: 118, dtype: str

In [13]:
import re

def extract_storage(memory, storage_type):
    matches = re.findall(
        rf'(\d+(?:\.\d+)?)\s*(GB|TB)\s*{storage_type}',
        memory
    )

    total = 0

    for value, unit in matches:
        value = float(value)

        if unit == 'TB':
            value *= 1024

        total += value

    return total

df['ssd_gb'] = df['Memory'].apply(lambda x: extract_storage(x, 'SSD'))
df['hdd_gb'] = df['Memory'].apply(lambda x: extract_storage(x, 'HDD'))
df['flash_gb'] = df['Memory'].apply(lambda x: extract_storage(x, 'Flash Storage'))
df['hybrid_gb'] = df['Memory'].apply(lambda x: extract_storage(x, 'Hybrid'))

In [14]:
df['cpu_speed_ghz'] = (
    df['Cpu']
    .str.extract(r'(\d+(?:\.\d+)?)GHz')[0]
    .astype(float)
)
df['cpu_family'] = df['Cpu'].str.extract(
    r'(Core i[3579]|Core M|Celeron|Pentium|Atom|A\d-Series|E-Series|Ryzen \d|Cortex)'
)[0]

df['res_width'] = df['ScreenResolution'].str.split(' ').str.get(-1).str.split('x').str[0].astype(int)
df['res_height'] = df['ScreenResolution'].str.split(' ').str.get(-1).str.split('x').str[1].astype(int)
df['is_touchscreen'] = df['ScreenResolution'].str.contains('Touchscreen').astype(int)

df['cpu_brand'] = df['Cpu'].str.split(' ').str.get(0)
df['gpu_brand'] = df['Gpu'].str.split(' ').str.get(0)
df.drop(columns=['ScreenResolution', 'Memory', 'Cpu', 'Gpu', 'Weight'], inplace=True)

In [15]:
df.head(20)

,laptop_ID,Company,Product,TypeName,Inches,Ram,OpSys,Price_euros,ssd_gb,hdd_gb,flash_gb,hybrid_gb,cpu_speed_ghz,cpu_family,res_width,res_height,is_touchscreen,cpu_brand,gpu_brand
0,1,Apple,MacBook Pro,Ultrabook,13.3,8GB,macOS,1339.69,128.0,0.0,0.0,0.0,2.3,Core i5,2560,1600,0,Intel,Intel
1,2,Apple,Macbook Air,Ultrabook,13.3,8GB,macOS,898.94,0.0,0.0,128.0,0.0,1.8,Core i5,1440,900,0,Intel,Intel
2,3,HP,250 G6,Notebook,15.6,8GB,No OS,575.00,256.0,0.0,0.0,0.0,2.5,Core i5,1920,1080,0,Intel,Intel
3,4,Apple,MacBook Pro,Ultrabook,15.4,16GB,macOS,2537.45,512.0,0.0,0.0,0.0,2.7,Core i7,2880,1800,0,Intel,AMD
4,5,Apple,MacBook Pro,Ultrabook,13.3,8GB,macOS,1803.60,256.0,0.0,0.0,0.0,3.1,Core i5,2560,1600,0,Intel,Intel
5,6,Acer,Aspire 3,Notebook,15.6,4GB,Windows 10,400.00,0.0,500.0,0.0,0.0,3.0,A9-Series,1366,768,0,AMD,AMD
6,7,Apple,MacBook Pro,Ultrabook,15.4,16GB,Mac OS X,2139.97,0.0,0.0,256.0,0.0,2.2,Core i7,2880,1800,0,Intel,Intel
7,8,Apple,Macbook Air,Ultrabook,13.3,8GB,macOS,1158.70,0.0,0.0,256.0,0.0,1.8,Core i5,1440,900,0,Intel,Intel
8,9,Asus,ZenBook UX430UN,Ultrabook,14.0,16GB,Windows 10,1495.00,512.0,0.0,0.0,0.0,1.8,Core i7,1920,1080,0,Intel,Nvidia
9,10,Acer,Swift 3,Ultrabook,14.0,8GB,Windows 10,770.00,256.0,0.0,0.0,0.0,1.6,Core i5,1920,1080,0,Intel,Intel
10,11,HP,250 G6,Notebook,15.6,4GB,No OS,393.90,0.0,500.0,0.0,0.0,2.5,Core i5,1366,768,0,Intel,Intel
11,12,HP,250 G6,Notebook,15.6,4GB,No OS,344.99,0.0,500.0,0.0,0.0,2.0,Core i3,1920,1080,0,Intel,Intel
12,13,Apple,MacBook Pro,Ultrabook,15.4,16GB,macOS,2439.97,256.0,0.0,0.0,0.0,2.8,Core i7,2880,1800,0,Intel,AMD
13,14,Dell,Inspiron 3567,Notebook,15.6,4GB,Windows 10,498.90,256.0,0.0,0.0,0.0,2.0,Core i3,1920,1080,0,Intel,AMD
14,15,Apple,"MacBook 12""",Ultrabook,12.0,8GB,macOS,1262.40,256.0,0.0,0.0,0.0,1.2,Core M,2304,1440,0,Intel,Intel
15,16,Apple,MacBook Pro,Ultrabook,13.3,8GB,macOS,1518.55,256.0,0.0,0.0,0.0,2.3,Core i5,2560,1600,0,Intel,Intel
16,17,Dell,Inspiron 3567,Notebook,15.6,8GB,Windows 10,745.00,256.0,0.0,0.0,0.0,2.7,Core i7,1920,1080,0,Intel,AMD
17,18,Apple,MacBook Pro,Ultrabook,15.4,16GB,macOS,2858.00,512.0,0.0,0.0,0.0,2.9,Core i7,2880,1800,0,Intel,AMD
18,19,Lenovo,IdeaPad 320-15IKB,Notebook,15.6,8GB,No OS,499.00,0.0,1024.0,0.0,0.0,2.4,Core i3,1920,1080,0,Intel,Nvidia
19,20,Dell,XPS 13,Ultrabook,13.3,8GB,Windows 10,979.00,128.0,0.0,0.0,0.0,1.6,Core i5,1920,1080,1,Intel,Intel

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   laptop_ID       1303 non-null   int64
 1   Company         1303 non-null   str
 2   Product         1303 non-null   str
 3   TypeName        1303 non-null   str
 4   Inches          1303 non-null   float64
 5   Ram             1303 non-null   str
 6   OpSys           1303 non-null   str
 7   Price_euros     1303 non-null   float64
 8   ssd_gb          1303 non-null   float64
 9   hdd_gb          1303 non-null   float64
 10  flash_gb        1303 non-null   float64
 11  hybrid_gb       1303 non-null   float64
 12  cpu_speed_ghz   1303 non-null   float64
 13  cpu_family      1283 non-null   str
 14  res_width       1303 non-null   int64
 15  res_height      1303 non-null   int64
 16  is_touchscreen  1303 non-null   int64
 17  cpu_brand       1303 non-null   object
 18  gpu_brand       1303 non-null   object
dtypes: float64(7), int64(4), object(2), str(6)
memory usage: 193.5+ KB

In [17]:
df['Ram'] = df['Ram'].str.replace('GB', '').astype(int)
df['cpu_family'] = df['cpu_family'].fillna(df['cpu_family'].mode()[0])

In [18]:
df.isnull().sum()

laptop_ID         0
Company           0
Product           0
TypeName          0
Inches            0
Ram               0
OpSys             0
Price_euros       0
ssd_gb            0
hdd_gb            0
flash_gb          0
hybrid_gb         0
cpu_speed_ghz     0
cpu_family        0
res_width         0
res_height        0
is_touchscreen    0
cpu_brand         0
gpu_brand         0
dtype: int64

In [29]:
df['Product'].unique()

<StringArray>
[                              'MacBook Pro',
                               'Macbook Air',
                                    '250 G6',
                                  'Aspire 3',
                           'ZenBook UX430UN',
                                   'Swift 3',
                             'Inspiron 3567',
                               'MacBook 12"',
                         'IdeaPad 320-15IKB',
                                    'XPS 13',
 ...
                               'GE62 Apache',
                            'Yoga 500-14IBD',
                      'ZenBook UX305CA-UBM1',
                            'Aspire ES1-531',
                       'Pavilion 15-AW003nv',
                          'Stream 11-Y000na',
 'X556UJ-XO044T (i7-6500U/4GB/500GB/GeForce',
                            'Yoga 500-14ISK',
       '15-AC110nv (i7-6500U/6GB/1TB/Radeon',
       'X553SA-XX031T (N3050/4GB/500GB/W10)']
Length: 618, dtype: str

In [20]:
df.head()

,laptop_ID,Company,Product,TypeName,Inches,Ram,OpSys,Price_euros,ssd_gb,hdd_gb,flash_gb,hybrid_gb,cpu_speed_ghz,cpu_family,res_width,res_height,is_touchscreen,cpu_brand,gpu_brand
0,1,Apple,MacBook Pro,Ultrabook,13.3,8,macOS,1339.69,128.0,0.0,0.0,0.0,2.3,Core i5,2560,1600,0,Intel,Intel
1,2,Apple,Macbook Air,Ultrabook,13.3,8,macOS,898.94,0.0,0.0,128.0,0.0,1.8,Core i5,1440,900,0,Intel,Intel
2,3,HP,250 G6,Notebook,15.6,8,No OS,575.00,256.0,0.0,0.0,0.0,2.5,Core i5,1920,1080,0,Intel,Intel
3,4,Apple,MacBook Pro,Ultrabook,15.4,16,macOS,2537.45,512.0,0.0,0.0,0.0,2.7,Core i7,2880,1800,0,Intel,AMD
4,5,Apple,MacBook Pro,Ultrabook,13.3,8,macOS,1803.60,256.0,0.0,0.0,0.0,3.1,Core i5,2560,1600,0,Intel,Intel

In [21]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
cat_cols = ['Company', 'TypeName', 'OpSys', 'cpu_brand', 'gpu_brand', 'cpu_family']
num_cols = ['Inches', 'Ram', 'res_width', 'res_height',
            'is_touchscreen', 'ssd_gb', 'hdd_gb', 'flash_gb', 'hybrid_gb', 'cpu_speed_ghz']

transformer = ColumnTransformer([
    ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols),
    ('num', StandardScaler(), num_cols)
])

In [22]:
from xgboost import XGBRegressor
from sklearn.pipeline import Pipeline
regressor = XGBRegressor(n_estimators=341, max_depth=5, learning_rate=0.06857396414176659, random_state=42)
pipeline = Pipeline([
    ('transformer', transformer),
    ('regressor', regressor)
])
pipeline

Pipeline(steps=[('transformer',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Company', 'TypeName',
                                                   'OpSys', 'cpu_brand',
                                                   'gpu_brand', 'cpu_family']),
                                                 ('num', StandardScaler(),
                                                  ['Inches', 'Ram', 'res_width',
                                                   'res_height',
                                                   'is_touchscreen', 'ssd_gb',
                                                   'hdd_gb', 'flash_gb',
                                                   'hybrid_gb',
                                                   'cpu_speed_ghz'])])),
                ('regressor',
                 XGBRegressor(ba...
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None,
                              learning_rate=0.06857396414176659, max_bin=None,
                              max_cat_threshold=None, max_cat_to_onehot=None,
                              max_delta_step=None, max_depth=5, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=341, n_jobs=None,
                              num_parallel_tree=None, ...))])

In [23]:
from sklearn.model_selection import train_test_split
X = df.drop('Price_euros', axis=1)
y = df['Price_euros']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train

,laptop_ID,Company,Product,TypeName,Inches,Ram,OpSys,ssd_gb,hdd_gb,flash_gb,hybrid_gb,cpu_speed_ghz,cpu_family,res_width,res_height,is_touchscreen,cpu_brand,gpu_brand
10,11,HP,250 G6,Notebook,15.6,4,No OS,0.0,500.0,0.0,0.0,2.50,Core i5,1366,768,0,Intel,Intel
147,150,Asus,X541NA (N3350/4GB/1TB/FHD/W10),Notebook,15.6,4,Windows 10,0.0,1024.0,0.0,0.0,1.10,Celeron,1920,1080,0,Intel,Intel
1287,1305,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,6,Windows 10,0.0,1024.0,0.0,0.0,2.50,Core i7,1366,768,0,Intel,AMD
767,776,Dell,Inspiron 7559,Gaming,15.6,16,Windows 10,128.0,1024.0,0.0,0.0,2.60,Core i7,3840,2160,1,Intel,Nvidia
816,825,Razer,Blade Stealth,Ultrabook,12.5,16,Windows 10,512.0,0.0,0.0,0.0,2.50,Core i7,3840,2160,1,Intel,Intel
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1095,1110,Acer,Aspire F5-573G,Notebook,15.6,8,Windows 10,256.0,1024.0,0.0,0.0,2.50,Core i5,1920,1080,0,Intel,Nvidia
1130,1145,HP,15-bs078cl (i7-7500U/8GB/2TB/W10),Notebook,15.6,8,Windows 10,0.0,2048.0,0.0,0.0,2.70,Core i7,1366,768,0,Intel,Intel
1294,1312,HP,Pavilion 15-AW003nv,Notebook,15.6,6,Windows 10,0.0,0.0,0.0,1024.0,2.90,A9-Series,1920,1080,0,AMD,AMD
860,871,Lenovo,ThinkPad E570,Notebook,15.6,8,Windows 10,0.0,1024.0,0.0,0.0,2.50,Core i5,1920,1080,0,Intel,Intel
1126,1141,Lenovo,Yoga Book,2 in 1 Convertible,10.1,4,Windows 10,0.0,0.0,64.0,0.0,1.44,Atom,1920,1200,1,Intel,Intel

In [24]:
pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)

In [25]:
import joblib
joblib.dump(pipeline, 'model.pkl')

['model.pkl']

In [26]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test,y_pred)
rmse = np.sqrt(mse)
print(f"Mean Squared Error: {mse}")
print(f"Mean Absolute Error: {mae}")
print(f"Root Mean Squared Error: {rmse}")

Mean Squared Error: 97341.182180196
Mean Absolute Error: 180.74661510014442
Root Mean Squared Error: 311.99548423045485

In [27]:
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor
from sklearn.model_selection import KFold, cross_val_score
X_train = transformer.fit_transform(X_train)

def Objective(trial):
    model = trial.suggest_categorical('model', ['LinearReg', 'SVR', 'RandomForest', 'GB', 'XGB'])

    if model == 'LinearReg':
        regressor = LinearRegression()
    elif model == 'SVR':
        kernel = trial.suggest_categorical('kernel', ['poly', 'rbf'])
        epsilon = trial.suggest_float('epsilon', 0.01, 0.5, log=True)
        regressor = SVR(kernel = kernel, epsilon = epsilon)
    elif model == 'RandomForest':
        n_estimators = trial.suggest_int('n_estimators', 0, 500)
        max_depth = trial.suggest_int('max_depth', 2, 30)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 2, 10)
        regressor = RandomForestRegressor(
            n_estimators = n_estimators,
            max_depth = max_depth,
            min_samples_split = min_samples_split,
            min_samples_leaf = min_samples_leaf
        )
    elif model == 'GB':
        n_estimators = trial.suggest_int('n_estimators_gb', 0, 500)
        learning_rate = trial.suggest_float('learning_rate_gb', 0.01, 0.1, log = True)
        max_depth = trial.suggest_int('max_depth_gb', 2, 30)
        regressor = GradientBoostingRegressor(
            n_estimators = n_estimators,
            learning_rate = learning_rate,
            max_depth = max_depth
        )
    else:
        n_estimators = trial.suggest_int('n_estimators_xgb', 0, 500)
        learning_rate = trial.suggest_float('learning_rate_xgb', 0.01, 0.1, log = True)
        max_depth = trial.suggest_int('max_depth_xgb', 2, 30)
        regressor = XGBRegressor(
            n_estimators = n_estimators,
            learning_rate = learning_rate,
            max_depth = max_depth
        )

    skf = KFold(n_splits = 5, shuffle = True, random_state=42)
    

    accuracy = cross_val_score(
        regressor,
        X_train,
        y_train,
        cv = skf,
        scoring = 'neg_mean_absolute_error'
    ).mean()
    score = -accuracy
    return score

In [28]:
import optuna
study = optuna.create_study(direction = 'minimize', sampler= optuna.samplers.TPESampler())
study.optimize(Objective, n_trials=50)

[I 2026-08-19 13:25:19,023] A new study created in memory with name: no-name-81732d19-8a77-4050-b81b-2d10188e801d
[I 2026-08-19 13:25:19,289] Trial 0 finished with value: 475.81337796414425 and parameters: {'model': 'SVR', 'kernel': 'poly', 'epsilon': 0.1911214991199554}. Best is trial 0 with value: 475.81337796414425.
[I 2026-08-19 13:25:19,547] Trial 1 finished with value: 497.92267478238557 and parameters: {'model': 'SVR', 'kernel': 'rbf', 'epsilon': 0.0637204295969225}. Best is trial 0 with value: 475.81337796414425.
[I 2026-08-19 13:25:20,044] Trial 2 finished with value: 264.11893166311165 and parameters: {'model': 'XGB', 'n_estimators_xgb': 18, 'learning_rate_xgb': 0.0702282258614214, 'max_depth_xgb': 30}. Best is trial 2 with value: 264.11893166311165.
[I 2026-08-19 13:25:20,151] Trial 3 finished with value: 240.51043114376472 and parameters: {'model': 'LinearReg'}. Best is trial 3 with value: 240.51043114376472.
[I 2026-08-19 13:25:21,479] Trial 4 finished with value: 222.2154875056496 and parameters: {'model': 'RandomForest', 'n_estimators': 55, 'max_depth': 29, 'min_samples_split': 2, 'min_samples_leaf': 6}. Best is trial 4 with value: 222.2154875056496.
[I 2026-08-19 13:25:21,551] Trial 5 finished with value: 240.51043114376472 and parameters: {'model': 'LinearReg'}. Best is trial 4 with value: 222.2154875056496.
[I 2026-08-19 13:25:21,801] Trial 6 finished with value: 497.9228129560337 and parameters: {'model': 'SVR', 'kernel': 'rbf', 'epsilon': 0.010558143647310558}. Best is trial 4 with value: 222.2154875056496.
[I 2026-08-19 13:25:21,871] Trial 7 finished with value: 240.51043114376472 and parameters: {'model': 'LinearReg'}. Best is trial 4 with value: 222.2154875056496.
[I 2026-08-19 13:25:37,216] Trial 8 finished with value: 212.8136160930792 and parameters: {'model': 'XGB', 'n_estimators_xgb': 462, 'learning_rate_xgb': 0.027546633131057516, 'max_depth_xgb': 24}. Best is trial 8 with value: 212.8136160930792.
[I 2026-08-19 13:25:37,335] Trial 9 finished with value: 240.51043114376472 and parameters: {'model': 'LinearReg'}. Best is trial 8 with value: 212.8136160930792.
[I 2026-08-19 13:25:44,968] Trial 10 finished with value: 210.5211445132506 and parameters: {'model': 'XGB', 'n_estimators_xgb': 469, 'learning_rate_xgb': 0.01547596052293367, 'max_depth_xgb': 14}. Best is trial 10 with value: 210.5211445132506.
[I 2026-08-19 13:25:55,238] Trial 11 finished with value: 213.22359041372502 and parameters: {'model': 'XGB', 'n_estimators_xgb': 487, 'learning_rate_xgb': 0.017155907379947963, 'max_depth_xgb': 18}. Best is trial 10 with value: 210.5211445132506.
[I 2026-08-19 13:25:57,684] Trial 12 finished with value: 198.5295731574751 and parameters: {'model': 'XGB', 'n_estimators_xgb': 482, 'learning_rate_xgb': 0.017760171959560377, 'max_depth_xgb': 8}. Best is trial 12 with value: 198.5295731574751.
[I 2026-08-19 13:26:14,059] Trial 13 finished with value: 237.7239161834888 and parameters: {'model': 'GB', 'n_estimators_gb': 267, 'learning_rate_gb': 0.04723718520790217, 'max_depth_gb': 18}. Best is trial 12 with value: 198.5295731574751.
[I 2026-08-19 13:26:14,976] Trial 14 finished with value: 205.34255216505426 and parameters: {'model': 'XGB', 'n_estimators_xgb': 408, 'learning_rate_xgb': 0.0111450361286299, 'max_depth_xgb': 5}. Best is trial 12 with value: 198.5295731574751.
[I 2026-08-19 13:26:15,365] Trial 15 finished with value: 260.9283926516558 and parameters: {'model': 'XGB', 'n_estimators_xgb': 330, 'learning_rate_xgb': 0.01000909754093278, 'max_depth_xgb': 2}. Best is trial 12 with value: 198.5295731574751.
[I 2026-08-19 13:26:15,706] Trial 16 finished with value: 429.4462919380413 and parameters: {'model': 'GB', 'n_estimators_gb': 31, 'learning_rate_gb': 0.01125548122302447, 'max_depth_gb': 4}. Best is trial 12 with value: 198.5295731574751.
[I 2026-08-19 13:26:19,645] Trial 17 finished with value: 330.1563523703387 and parameters: {'model': 'RandomForest', 'n_estimators': 476, 'max_depth': 2, 'min_samples_split': 10, 'min_samples_leaf': 10}. Best is trial 12 with value: 198.5295731574751.
[I 2026-08-19 13:26:20,168] Trial 18 finished with value: 207.21680379871628 and parameters: {'model': 'XGB', 'n_estimators_xgb': 308, 'learning_rate_xgb': 0.022721742278429307, 'max_depth_xgb': 4}. Best is trial 12 with value: 198.5295731574751.
[I 2026-08-19 13:26:22,117] Trial 19 finished with value: 204.5190746370329 and parameters: {'model': 'XGB', 'n_estimators_xgb': 336, 'learning_rate_xgb': 0.010293131283192564, 'max_depth_xgb': 9}. Best is trial 12 with value: 198.5295731574751.
[I 2026-08-19 13:26:23,986] Trial 20 finished with value: 203.48666926674954 and parameters: {'model': 'XGB', 'n_estimators_xgb': 240, 'learning_rate_xgb': 0.037999930945417176, 'max_depth_xgb': 11}. Best is trial 12 with value: 198.5295731574751.
[I 2026-08-19 13:26:25,600] Trial 21 finished with value: 204.47239537784603 and parameters: {'model': 'XGB', 'n_estimators_xgb': 208, 'learning_rate_xgb': 0.04108357252473552, 'max_depth_xgb': 11}. Best is trial 12 with value: 198.5295731574751.
[I 2026-08-19 13:26:27,639] Trial 22 finished with value: 206.79426690986924 and parameters: {'model': 'XGB', 'n_estimators_xgb': 174, 'learning_rate_xgb': 0.04440905271270303, 'max_depth_xgb': 12}. Best is trial 12 with value: 198.5295731574751.
[I 2026-08-19 13:26:29,340] Trial 23 finished with value: 199.0943632886744 and parameters: {'model': 'XGB', 'n_estimators_xgb': 186, 'learning_rate_xgb': 0.04129685247458156, 'max_depth_xgb': 9}. Best is trial 12 with value: 198.5295731574751.
[I 2026-08-19 13:26:30,163] Trial 24 finished with value: 198.62988487576123 and parameters: {'model': 'XGB', 'n_estimators_xgb': 155, 'learning_rate_xgb': 0.04060382381779731, 'max_depth_xgb': 7}. Best is trial 12 with value: 198.5295731574751.
[I 2026-08-19 13:26:43,758] Trial 25 finished with value: 239.11964305684833 and parameters: {'model': 'GB', 'n_estimators_gb': 490, 'learning_rate_gb': 0.0989230132641067, 'max_depth_gb': 30}. Best is trial 12 with value: 198.5295731574751.
[I 2026-08-19 13:26:45,598] Trial 26 finished with value: 207.94172507209015 and parameters: {'model': 'RandomForest', 'n_estimators': 56, 'max_depth': 20, 'min_samples_split': 6, 'min_samples_leaf': 2}. Best is trial 12 with value: 198.5295731574751.
[I 2026-08-19 13:26:45,972] Trial 27 finished with value: 198.16884252039264 and parameters: {'model': 'XGB', 'n_estimators_xgb': 92, 'learning_rate_xgb': 0.07294883634377804, 'max_depth_xgb': 7}. Best is trial 27 with value: 198.16884252039264.
[I 2026-08-19 13:26:46,192] Trial 28 finished with value: 201.58727966928046 and parameters: {'model': 'XGB', 'n_estimators_xgb': 58, 'learning_rate_xgb': 0.08133468684535192, 'max_depth_xgb': 6}. Best is trial 27 with value: 198.16884252039264.
[I 2026-08-19 13:26:46,484] Trial 29 finished with value: 475.80632798598936 and parameters: {'model': 'SVR', 'kernel': 'poly', 'epsilon': 0.38889569856083983}. Best is trial 27 with value: 198.16884252039264.
[I 2026-08-19 13:26:47,977] Trial 30 finished with value: 212.84872343080906 and parameters: {'model': 'XGB', 'n_estimators_xgb': 97, 'learning_rate_xgb': 0.06020137448309586, 'max_depth_xgb': 16}. Best is trial 27 with value: 198.16884252039264.
[I 2026-08-19 13:26:48,555] Trial 31 finished with value: 198.59045113653605 and parameters: {'model': 'XGB', 'n_estimators_xgb': 127, 'learning_rate_xgb': 0.05413744266442122, 'max_depth_xgb': 8}. Best is trial 27 with value: 198.16884252039264.
[I 2026-08-19 13:26:48,983] Trial 32 finished with value: 195.69709586745603 and parameters: {'model': 'XGB', 'n_estimators_xgb': 119, 'learning_rate_xgb': 0.09439710179332664, 'max_depth_xgb': 7}. Best is trial 32 with value: 195.69709586745603.
[I 2026-08-19 13:26:49,266] Trial 33 finished with value: 475.8196715970824 and parameters: {'model': 'SVR', 'kernel': 'poly', 'epsilon': 0.01036480788952999}. Best is trial 32 with value: 195.69709586745603.
[I 2026-08-19 13:26:49,701] Trial 34 finished with value: 196.29590777837245 and parameters: {'model': 'XGB', 'n_estimators_xgb': 124, 'learning_rate_xgb': 0.09789678409465592, 'max_depth_xgb': 7}. Best is trial 32 with value: 195.69709586745603.
[I 2026-08-19 13:26:49,845] Trial 35 finished with value: 215.09669048266082 and parameters: {'model': 'XGB', 'n_estimators_xgb': 67, 'learning_rate_xgb': 0.09994804836073266, 'max_depth_xgb': 3}. Best is trial 32 with value: 195.69709586745603.
[I 2026-08-19 13:26:53,708] Trial 36 finished with value: 330.4261809144658 and parameters: {'model': 'RandomForest', 'n_estimators': 449, 'max_depth': 2, 'min_samples_split': 2, 'min_samples_leaf': 10}. Best is trial 32 with value: 195.69709586745603.
[I 2026-08-19 13:26:54,029] Trial 37 finished with value: 196.58459863071488 and parameters: {'model': 'XGB', 'n_estimators_xgb': 101, 'learning_rate_xgb': 0.09757302216916046, 'max_depth_xgb': 6}. Best is trial 32 with value: 195.69709586745603.
[I 2026-08-19 13:26:54,132] Trial 38 finished with value: 240.51043114376472 and parameters: {'model': 'LinearReg'}. Best is trial 32 with value: 195.69709586745603.
[I 2026-08-19 13:26:54,381] Trial 39 finished with value: 497.9226759042842 and parameters: {'model': 'SVR', 'kernel': 'rbf', 'epsilon': 0.06329171090675141}. Best is trial 32 with value: 195.69709586745603.
[I 2026-08-19 13:26:54,439] Trial 40 finished with value: 521.9197031347975 and parameters: {'model': 'GB', 'n_estimators_gb': 6, 'learning_rate_gb': 0.010316234796728475, 'max_depth_gb': 2}. Best is trial 32 with value: 195.69709586745603.
[I 2026-08-19 13:26:54,784] Trial 41 finished with value: 196.57039196953687 and parameters: {'model': 'XGB', 'n_estimators_xgb': 114, 'learning_rate_xgb': 0.09328007711865068, 'max_depth_xgb': 6}. Best is trial 32 with value: 195.69709586745603.
[I 2026-08-19 13:26:55,094] Trial 42 finished with value: 198.06059601418357 and parameters: {'model': 'XGB', 'n_estimators_xgb': 110, 'learning_rate_xgb': 0.0969033107591843, 'max_depth_xgb': 5}. Best is trial 32 with value: 195.69709586745603.
[I 2026-08-19 13:26:55,526] Trial 43 finished with value: 195.8448016193152 and parameters: {'model': 'XGB', 'n_estimators_xgb': 135, 'learning_rate_xgb': 0.09910906190662429, 'max_depth_xgb': 5}. Best is trial 32 with value: 195.69709586745603.
[I 2026-08-19 13:26:55,861] Trial 44 finished with value: 207.00362326381156 and parameters: {'model': 'XGB', 'n_estimators_xgb': 146, 'learning_rate_xgb': 0.08604003622765581, 'max_depth_xgb': 3}. Best is trial 32 with value: 195.69709586745603.
[I 2026-08-19 13:26:55,980] Trial 45 finished with value: 240.51043114376472 and parameters: {'model': 'LinearReg'}. Best is trial 32 with value: 195.69709586745603.
[I 2026-08-19 13:26:56,126] Trial 46 finished with value: 253.5533910639499 and parameters: {'model': 'XGB', 'n_estimators_xgb': 20, 'learning_rate_xgb': 0.08419786176935753, 'max_depth_xgb': 5}. Best is trial 32 with value: 195.69709586745603.
[I 2026-08-19 13:26:56,825] Trial 47 finished with value: 200.47134471645924 and parameters: {'model': 'XGB', 'n_estimators_xgb': 62, 'learning_rate_xgb': 0.09624988538077153, 'max_depth_xgb': 10}. Best is trial 32 with value: 195.69709586745603.
[I 2026-08-19 13:26:57,066] Trial 48 finished with value: 225.76405971897196 and parameters: {'model': 'XGB', 'n_estimators_xgb': 130, 'learning_rate_xgb': 0.06477970103497839, 'max_depth_xgb': 2}. Best is trial 32 with value: 195.69709586745603.
[I 2026-08-19 13:27:04,451] Trial 49 finished with value: 211.19244744093467 and parameters: {'model': 'RandomForest', 'n_estimators': 253, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 2}. Best is trial 32 with value: 195.69709586745603.